import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {AlertTriangle,BrainCircuit,Check,Download,FileSpreadsheet,Filter,Plus,RefreshCw,Search,Send,ShieldCheck,Trash2,Upload,WalletCards,X} from 'lucide-react';
import {api,apiError,getData} from '../lib/api';
import {Card,money,PageIntro,Progress} from '../components/UI';

type Tx={id:string;amount:number;transaction_type:'income'|'expense'|'transfer';category:string;merchant:string;description?:string;payment_method?:string;date:string;risk?:string};
const categories=['Food','Transport','Shopping','Bills','Education','Entertainment','Healthcare','Subscriptions','Other'];
function Status({error,onRetry}:{error:string,onRetry?:()=>void}){return <div className="apiState errorState"><AlertTriangle/><div><b>We could not load this data.</b><p>{error}</p></div>{onRetry&&<button onClick={onRetry}><RefreshCw/>Try again</button>}</div>}
function Empty({title,text,action}:{title:string,text:string,action?:React.ReactNode}){return <div className="apiState emptyState"><WalletCards/><div><b>{title}</b><p>{text}</p></div>{action}</div>}
function Spinner(){return <div className="premiumLoader"><i/><i/><i/></div>}
function download(name:string,text:string,type='text/csv'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}

export function Transactions(){
  const [rows,setRows]=useState<Tx[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState('all'),[show,setShow]=useState(false);
  async function load(){setLoading(true);setError('');try{setRows(await getData<Tx[]>('/transactions'))}catch(e){setError(apiError(e))}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const filtered=rows.filter(x=>(x.merchant+x.category+(x.description||'')).toLowerCase().includes(query.toLowerCase())&&(type==='all'||x.transaction_type===type));
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={merchant:String(f.get('merchant')),category:String(f.get('category')),amount:Number(f.get('amount')),transaction_type:String(f.get('transaction_type')),date:String(f.get('date')),description:String(f.get('description')||''),payment_method:String(f.get('payment_method')||'')};setError('');try{const r=await api.post('/transactions',body);setRows([r.data,...rows]);setShow(false);setNotice('Transaction saved and included in anomaly analysis.')}catch(err){setError(apiError(err,'The transaction could not be saved.'))}}
  async function remove(id:string){if(!confirm('Delete this transaction?'))return;try{await api.delete(`/transactions/${id}`);setRows(rows.filter(x=>x.id!==id))}catch(e){setError(apiError(e,'The transaction could not be deleted.'))}}
  async function upload(file?:File){if(!file)return;const form=new FormData();form.append('file',file);try{const r=await api.post('/transactions/upload',form,{timeout:60000});setNotice(`${r.data.imported} transactions imported; ${r.data.skipped} skipped.`);load()}catch(e){setError(apiError(e,'The CSV could not be imported.'))}}
  return <><PageIntro eyebrow="FINANCIAL ACTIVITY" title="Transactions" desc="Track income and expenses, import anonymized CSV data and review financial activity." action={<button className="primary" onClick={()=>setShow(true)}><Plus/>Add transaction</button>}/><div className="sampleLabel"><span>SAMPLE DATA</span>The demo account contains fictional transactions only.</div>{notice&&<div className="safetyNotice"><Check/>{notice}</div>}{error&&<Status error={error} onRetry={load}/>}<Card><div className="toolbar"><label><Search/><input aria-label="Search transactions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant, category or description"/></label><button onClick={()=>setType(type==='all'?'expense':type==='expense'?'income':'all')}><Filter/>{type==='all'?'All types':type}</button><label className="importBtn"><Upload/>Import CSV<input type="file" accept=".csv,text/csv" onChange={e=>upload(e.target.files?.[0])}/></label></div>{loading?<Spinner/>:!filtered.length?<Empty title="No matching transactions" text="Add a transaction or change your filters."/>:<div className="dataTable modernDataTable"><div className="tr th"><span>Merchant</span><span>Category</span><span>Date</span><span>Type</span><span>Amount</span><span/></div>{filtered.map(t=><div className="tr" key={t.id}><b>{t.merchant}</b><span>{t.category}</span><span>{t.date}</span><span><i className={`tag ${t.transaction_type}`}>{t.transaction_type}</i></span><strong className={t.transaction_type==='income'?'positive':''}>{t.transaction_type==='income'?'+':'-'}{money(t.amount)}</strong><button aria-label={`Delete ${t.merchant}`} onClick={()=>remove(t.id)}><Trash2/></button></div>)}</div>}</Card>{show&&<div className="modal modernModal"><form onSubmit={add}><button type="button" className="modalX" onClick={()=>setShow(false)}><X/></button><span>NEW FINANCIAL ACTIVITY</span><h3>Add transaction</h3><p>Use financial details only. Never enter passwords, OTPs, PINs or card security codes.</p><input name="merchant" required maxLength={120} placeholder="Merchant or source"/><div className="formSplit"><select name="transaction_type" required><option value="expense">Expense</option><option value="income">Income</option><option value="transfer">Transfer</option></select><select name="category" required>{categories.map(x=><option key={x}>{x}</option>)}</select></div><div className="formSplit"><input name="amount" required type="number" min=".01" step=".01" placeholder="Amount"/><input name="date" required type="date" defaultValue={new Date().toISOString().slice(0,10)}/></div><input name="payment_method" maxLength={50} placeholder="Payment method (optional)"/><textarea name="description" maxLength={500} placeholder="Description (optional)"/><button className="primary">Save transaction</button></form></div>}</>
}

export function Analytics(){
  const [rows,setRows]=useState<Tx[]>([]),[summary,setSummary]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  async function load(){setLoading(true);setError('');try{const [t,s]=await Promise.all([getData<Tx[]>('/transactions'),getData<any>('/analytics/summary')]);setRows(t);setSummary(s)}catch(e){setError(apiError(e))}finally{setLoading(false)}}
  useEffect(()=>{load()},[]);
  const monthly=useMemo(()=>{const m=new Map<string,{month:string;income:number;expense:number}>();rows.forEach(x=>{const k=x.date.slice(0,7),r=m.get(k)||{month:k,income:0,expense:0};r[x.transaction_type==='income'?'income':'expense']+=x.amount;m.set(k,r)});return [...m.values()].sort((a,b)=>a.month.localeCompare(b.month)).slice(-8)},[rows]);
  const cats=useMemo(()=>{const m=new Map<string,number>();rows.filter(x=>x.transaction_type==='expense').forEach(x=>m.set(x.category,(m.get(x.category)||0)+x.amount));return [...m].map(([name,value],i)=>({name,value,fill:['#7c8cff','#34d399','#facc15','#fb923c','#a78bfa','#f87171'][i%6]})).sort((a,b)=>b.value-a.value)},[rows]);
  if(loading)return <><PageIntro eyebrow="FINANCIAL INSIGHTS" title="Analytics" desc="Loading your financial activity…"/><Spinner/></>;
  return <><PageIntro eyebrow="FINANCIAL INSIGHTS" title="Analytics" desc="Income, expenses, category allocation and spending trends from your transaction history." action={<button className="secondaryAction" onClick={load}><RefreshCw/>Refresh</button>}/>{error&&<Status error={error} onRetry={load}/>} {summary&&<div className="metrics"><Metric label="Income" value={money(summary.income)}/><Metric label="Expenses" value={money(summary.expenses)}/><Metric label="Balance" value={money(summary.balance)}/><Metric label="Savings rate" value={`${summary.savings_rate}%`}/></div>}<div className="grid"><Card className="chart wide"><h3>Income and spending trend</h3>{monthly.length?<ResponsiveContainer height={290} width="100%"><AreaChart data={monthly}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="month"/><YAxis hide/><Tooltip/><Area dataKey="income" stroke="#34d399" fill="#34d39918"/><Area dataKey="expense" stroke="#7c8cff" fill="#7c8cff18"/></AreaChart></ResponsiveContainer>:<Empty title="Not enough history" text="Add transactions across multiple dates to build a trend."/ >}</Card><Card><h3>Category breakdown</h3>{cats.length?<><ResponsiveContainer height={210} width="100%"><PieChart><Pie data={cats} dataKey="value" nameKey="name" innerRadius={52} outerRadius={76}>{cats.map(x=><Cell key={x.name} fill={x.fill}/>)}</Pie><Tooltip formatter={(v)=>money(Number(v))}/></PieChart></ResponsiveContainer>{cats.slice(0,6).map(x=><p className="split" key={x.name}><span>{x.name}</span><b>{money(x.value)}</b></p>)}</>:<Empty title="No expenses yet" text="Expense categories will appear here."/ >}</Card></div></>
}
function Metric({label,value}:{label:string,value:string}){return <Card className="metric"><span>{label}</span><strong>{value}</strong><small>Based on available records</small></Card>}

export function Anomalies(){
  const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[show,setShow]=useState(false),[result,setResult]=useState<any>(null);
  async function load(){setLoading(true);setError('');try{setRows(await getData<any[]>('/transactions/anomalies'))}catch(e){setError(apiError(e))}finally{setLoading(false)}}useEffect(()=>{load()},[]);
  async function evaluate(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),body={merchant:String(f.get('merchant')),category:String(f.get('category')),amount:Number(f.get('amount')),payment_method:String(f.get('payment_method')||''),description:String(f.get('description')||'')};try{const r=await api.post('/anomaly/evaluate',body);setResult(r.data)}catch(err){setError(apiError(err,'The transaction could not be evaluated.'))}}
  return <><PageIntro eyebrow="EXPLAINABLE ANOMALY DETECTION" title="Transaction risk analysis" desc="Review model signals without treating them as definitive proof of fraud." action={<button className="primary" onClick={()=>setShow(true)}>Evaluate transaction</button>}/>{error&&<Status error={error} onRetry={load}/>}<Card>{loading?<Spinner/>:!rows.length?<Empty title="No transactions to scan" text="Add transaction history before running anomaly detection."/>:<div className="dataTable"><div className="tr anomalyTr th"><span>Transaction</span><span>Amount</span><span>Score</span><span>Risk</span><span>Reason</span><span>Date</span></div>{rows.sort((a,b)=>b.score_100-a.score_100).map(x=><div className="tr anomalyTr" key={x.transaction_id}><b>{x.merchant||'Transaction'}</b><span>{money(x.amount||0)}</span><strong>{x.score_100}/100</strong><span><i className={`tag ${x.risk_level}`}>{x.risk_level}</i></span><span>{x.reason}</span><span>{String(x.date||'')}</span></div>)}</div>}</Card>{show&&<div className="modal modernModal"><form onSubmit={evaluate}><button type="button" className="modalX" onClick={()=>{setShow(false);setResult(null)}}><X/></button><span>PROSPECTIVE RISK CHECK</span><h3>Evaluate a transaction</h3>{!result?<><input required name="merchant" placeholder="Merchant or recipient"/><select required name="category">{categories.map(x=><option key={x}>{x}</option>)}</select><input required name="amount" type="number" min=".01" step=".01" placeholder="Amount"/><input name="payment_method" placeholder="Payment method"/><textarea name="description" placeholder="Optional context"/><button className="primary">Check transaction pattern</button></>:<div className={`evaluationResult ${result.risk_level}`}><strong>{result.score_100}/100</strong><h3>{result.classification}</h3><p>{result.reason}</p><div><b>Recommended next action</b><span>{result.recommended_action}</span></div><small>This is a model signal, not proof that the transaction is fraudulent.</small></div>}</form></div>}</>
}

export function Forecasts(){
  const [data,setData]=useState<any[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true);async function load(){setLoading(true);setError('');try{setData(await getData<any[]>('/prediction/expenses'))}catch(e){setError(apiError(e))}finally{setLoading(false)}}useEffect(()=>{load()},[]);
  return <><PageIntro eyebrow="ESTIMATED EXPENSES" title="Expense prediction" desc="Forecasts are estimates based on available transaction history, not guaranteed outcomes." action={<button className="secondaryAction" onClick={load}><RefreshCw/>Refresh</button>}/>{error&&<Status error={error} onRetry={load}/>}<div className="predictionGrid">{loading?<Spinner/>:data.length?data.map(x=><Card key={x.month_ahead}><small>MONTH +{x.month_ahead}</small><h3>{money(x.predicted)}</h3><p>Estimated range {money(x.lower)} – {money(x.upper)}</p><Progress value={x.confidence*100}/><footer>{Math.round(x.confidence*100)}% model confidence · {x.model}</footer></Card>):<Empty title="Prediction unavailable" text="Add expense history across several months to generate an estimate."/ >}</div>{data.length>0&&<Card className="chart"><h3>Expected spending range</h3><ResponsiveContainer width="100%" height={300}><BarChart data={data}><CartesianGrid vertical={false} stroke="var(--chart-grid)"/><XAxis dataKey="month_ahead" tickFormatter={v=>`Month ${v}`}/><YAxis hide/><Tooltip formatter={(v)=>money(Number(v))}/><Bar dataKey="predicted" fill="#7c8cff" radius={[7,7,0,0]}/><Bar dataKey="upper" fill="#7c8cff44" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></Card>}</>
}

export function Budgets(){const [items,setItems]=useState<any[]>([]),[show,setShow]=useState(false),[error,setError]=useState('');async function load(){try{setItems(await getData<any[]>('/budgets'))}catch(e){setError(apiError(e))}}useEffect(()=>{load()},[]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/budgets',{category:f.get('category'),limit:Number(f.get('limit')),start_date:f.get('start_date'),end_date:f.get('end_date')});setShow(false);load()}catch(err){setError(apiError(err))}}return <><PageIntro eyebrow="PLANNING" title="Budgets" desc="Category limits backed by your saved account data." action={<button className="primary" onClick={()=>setShow(true)}><Plus/>New budget</button>}/>{error&&<Status error={error}/>}<div className="listCards">{items.length?items.map(x=>{const p=Math.min(100,(x.spent||0)/x.limit*100);return <Card key={x.id}><div className="listHead"><div><small>ACTIVE BUDGET</small><h3>{x.category}</h3><span>{money(x.spent||0)} of {money(x.limit)}</span></div><strong>{p.toFixed(0)}%</strong></div><Progress value={p} tone={p>80?'orange':'mint'}/><p className="insight">{p>80?'Review this category before additional spending.':'Spending remains within the configured limit.'}</p></Card>}):<Empty title="No budgets yet" text="Create a budget to monitor a spending category." action={<button className="primary" onClick={()=>setShow(true)}>Create budget</button>}/>}</div>{show&&<SimplePlanModal title="Create budget" onClose={()=>setShow(false)} onSubmit={add} fields="budget"/>}</>}
export function Goals(){const [items,setItems]=useState<any[]>([]),[show,setShow]=useState(false),[error,setError]=useState('');async function load(){try{setItems(await getData<any[]>('/goals'))}catch(e){setError(apiError(e))}}useEffect(()=>{load()},[]);async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api.post('/goals',{name:f.get('name'),target_amount:Number(f.get('target_amount')),current_amount:Number(f.get('current_amount')||0),deadline:f.get('deadline')});setShow(false);load()}catch(err){setError(apiError(err))}}return <><PageIntro eyebrow="PLANNING" title="Financial goals" desc="Track progress toward a clear amount and deadline." action={<button className="primary" onClick={()=>setShow(true)}><Plus/>New goal</button>}/>{error&&<Status error={error}/>}<div className="listCards">{items.length?items.map(x=>{const p=Math.min(100,x.current_amount/x.target_amount*100);return <Card key={x.id}><div className="listHead"><div><small>{x.status?.toUpperCase()||'ACTIVE GOAL'}</small><h3>{x.name}</h3><span>{money(x.current_amount)} of {money(x.target_amount)}</span></div><strong>{p.toFixed(0)}%</strong></div><Progress value={p}/><p className="insight">Target date: <b>{x.deadline}</b>. Estimates depend on future savings behavior.</p></Card>}):<Empty title="No goals yet" text="Create a goal to track your progress." action={<button className="primary" onClick={()=>setShow(true)}>Create goal</button>}/>}</div>{show&&<SimplePlanModal title="Create goal" onClose={()=>setShow(false)} onSubmit={add} fields="goal"/>}</>}
function SimplePlanModal({title,onClose,onSubmit,fields}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void;fields:'budget'|'goal'}){const now=new Date(),later=new Date(Date.now()+90*86400000);return <div className="modal modernModal"><form onSubmit={onSubmit}><button type="button" className="modalX" onClick={onClose}><X/></button><span>FINANCIAL PLANNING</span><h3>{title}</h3>{fields==='budget'?<><select name="category">{categories.map(x=><option key={x}>{x}</option>)}</select><input required name="limit" type="number" min="1" placeholder="Limit"/><div className="formSplit"><input required name="start_date" type="date" defaultValue={now.toISOString().slice(0,10)}/><input required name="end_date" type="date" defaultValue={later.toISOString().slice(0,10)}/></div></>:<><input required name="name" maxLength={120} placeholder="Goal name"/><div className="formSplit"><input required name="target_amount" type="number" min="1" placeholder="Target amount"/><input name="current_amount" type="number" min="0" placeholder="Already saved"/></div><input required name="deadline" type="date" defaultValue={later.toISOString().slice(0,10)}/></>}<button className="primary">Save</button></form></div>}

export function Reports(){const [report,setReport]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);async function generate(){setLoading(true);try{const r=await getData<any>('/reports/monthly');setReport(r)}catch(e){setError(apiError(e))}finally{setLoading(false)}}function exportCsv(){if(!report)return;download('finguard-monthly-report.csv',`metric,value\nperiod,${report.period}\nincome,${report.summary.income}\nexpenses,${report.summary.expenses}\nbalance,${report.summary.balance}\nsavings_rate,${report.summary.savings_rate}`)}return <><PageIntro eyebrow="REPORTING" title="Financial reports" desc="Generate a report from current backend records—not placeholder values." action={<button className="primary" onClick={generate} disabled={loading}><Download/>{loading?'Generating…':'Generate report'}</button>}/>{error&&<Status error={error}/>} {!report?<Empty title="No report generated" text="Generate a monthly report from your saved financial records."/>:<div className="modelGrid"><Card><Download/><h3>{report.period}</h3><p>Income {money(report.summary.income)} · Expenses {money(report.summary.expenses)}</p><button className="primary" onClick={exportCsv}><FileSpreadsheet/>Download CSV</button></Card><Card><ShieldCheck/><h3>Guard score {report.summary.guard_score}</h3><p>Savings rate {report.summary.savings_rate}% · Generated for the authenticated account.</p></Card></div>}</>}

export function Assistant(){type Msg={who:'user'|'ai';text:string;sources?:string[];model?:string};const [msgs,setMsgs]=useState<Msg[]>([{who:'ai',text:'Ask about your authenticated transactions, budgets, goals, scam analyses or incidents.'}]),[q,setQ]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');async function send(){const question=q.trim();if(!question||loading)return;const prior=msgs;setQ('');setMsgs([...prior,{who:'user',text:question}]);setLoading(true);setError('');try{const history=prior.slice(-6).map(m=>({role:m.who==='ai'?'assistant':'user',content:m.text}));const r=await api.post('/ai/ask',{question,history},{timeout:60000});setMsgs([...prior,{who:'user',text:question},{who:'ai',text:r.data.answer,sources:r.data.sources,model:r.data.model}])}catch(e){setError(apiError(e,'FinGuard AI could not answer right now.'))}finally{setLoading(false)}}return <><PageIntro eyebrow="GROUNDED AI" title="FinGuard AI" desc="Answers use retrieved account records. If information is missing, FinGuard should say so."/><div className="aiLayout"><Card className="chat aiChat"><div className="messages">{msgs.map((m,i)=><div className={m.who} key={i}>{m.who==='ai'&&<BrainCircuit/>}<div><p>{m.text}</p>{m.sources&&<footer><span>{m.model}</span>{m.sources.map(x=><i key={x}>{x}</i>)}</footer>}</div></div>)}{loading&&<div className="ai thinking"><BrainCircuit/><p><i/><i/><i/> Reading your account context…</p></div>}</div>{error&&<Status error={error}/>}<div className="composer"><input aria-label="Ask FinGuard AI" value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Ask a financial safety question…"/><button onClick={send} disabled={!q.trim()||loading} aria-label="Send question"><Send/></button></div></Card><aside className="aiContext"><Card><small>DATA BOUNDARY</small><h3>Grounded answers</h3><p><Check/>Authenticated records only</p><p><Check/>Sources shown with answers</p><p><Check/>No guaranteed predictions</p></Card></aside></div></>}

export function Settings(){const [me,setMe]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState('');useEffect(()=>{getData('/users/me').then(setMe).catch(e=>setError(apiError(e)))},[]);async function password(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('new')!==f.get('confirm'))return setError('New passwords do not match.');try{await api.post('/auth/change-password',{current_password:f.get('current'),new_password:f.get('new')});setNotice('Password changed. Sign in again on your next session.');e.currentTarget.reset()}catch(err){setError(apiError(err))}}return <><PageIntro eyebrow="ACCOUNT SECURITY" title="Settings" desc="Review account details and update your password securely." />{error&&<Status error={error}/>} {notice&&<div className="safetyNotice"><Check/>{notice}</div>}<div className="settingsGrid"><Card><h3>Profile</h3><p className="split"><span>Name</span><b>{me?.name||'Loading…'}</b></p><p className="split"><span>Email</span><b>{me?.email||'Loading…'}</b></p><p className="split"><span>Currency</span><b>{me?.currency||'—'}</b></p><p className="split"><span>Language</span><b>{me?.language||'—'}</b></p></Card><Card><h3>Change password</h3><form className="securityForm" onSubmit={password}><input required type="password" minLength={10} name="current" autoComplete="current-password" placeholder="Current password"/><input required type="password" minLength={10} name="new" autoComplete="new-password" placeholder="New password"/><input required type="password" minLength={10} name="confirm" autoComplete="new-password" placeholder="Confirm new password"/><button className="primary">Update password</button></form></Card><Card><h3>Security status</h3><p className="split"><span>Authentication</span><b className="good">JWT enabled</b></p><p className="split"><span>Password storage</span><b className="good">Argon2 hashed</b></p><p>Two-factor authentication is not currently configured. FinGuard does not claim otherwise.</p></Card></div></>}